### ISSUE TITLE
Massive file size!!! Over 500MB!!

### ISSUE THREAD

**Issue by bnichs5** [truefedex/GeckoViewNativeWebApp#2]
Big fan of your TVBro app. Was looking around for something simmilar that used Geckoview and came across this. I downloaded your code and imported it into Android Studio. I compiled it and the output was a 500MB apk file! Is there anyway to get that number down to under 100MB?

**Comment by truefedex** [comment]
I think you got debug version. In this case you should just try to build release version and probably enable this in build gradle for release build variant:
`minifyEnabled true`

**Comment by bnichs5** [comment]
Thank you.  That definitely helped. Still big though. For the time being I just changed the main geckoview to arm-v7a which dramatically reduced apk size. I think that should suit my needs for the moment. Thanks again
